### ISSUE TITLE
Add the `titiler` service to the deployment stack

### ISSUE THREAD

**Issue by zachsa** [SAEON/mnemosyne#10]
This involves updating the stack.yml file (docker-compose.yml for Docker Swarm) to include an additional server (that is titiler). Here is the file that needs to be updated: https://github.com/SAEON/mnemosyne/blob/stable/deploy/stable/stack.yml

For a reference on how to add a service that uses a pre-built image available on Docker Hub - https://github.com/SAEON/elk-stack/blob/main/v8/stack.yml#L55-L80. 

(https://hub.docker.com/r/developmentseed/titiler)

**Comment by GMoncrieff** [comment]
For interest sake, how would I test this while developing or before I send a PR? At present, my understanding is that I would have to deploy the Mnemosyne stack to a test machine

**Comment by zachsa** [comment]
you can deploy the mnemosyne stack on your local machine - create a single node Docker swarm: https://docs.docker.com/engine/reference/commandline/swarm_init/

Running `docker swarm init` will just register your docker engine as a manager node, meaning you can run docker swarm CLI commands on it. This doesn't effect your Docker install in any way so far aw I know (at least I have never noticed a difference in the way that docker works when registered as a single node swarm compared to not).

`docker compose up` and `docker stack deploy` are very similar.

With Docker Compose you have a yml file that specifies a number of containers that go up together and should be on the same network - that's the same with Docker Swarm. The compose file specifies a number of containers that go up together. Just the terminology is different. So with `compose` the result is a number of containers. 

Likewise with `stack deploy`, you get a number of containers. But each container belongs to a service. And each service belongs to a stack.

**Comment by zachsa** [comment]
Is this still needed?

**Comment by zachsa** [comment]
Moved the titler service to the `titiler` branch for now

**Comment by zachsa** [comment]
I remember now - this was moved to here: https://github.com/SAEON/titiler
